//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_DAM.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Proyecto_DAM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width,initial-scale=1&quot;&gt;
        ///    &lt;meta name=&quot;x-apple-disable-message-reformatting&quot;&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///
        ///    &lt;style&gt;
        ///        table,
        ///        td,
        ///        div,
        ///        h1,
        ///        p {
        ///            font-family: Arial, sans-serif;
        ///        }
        ///
        ///        @media screen and (max-width: 530px) {
        ///             [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string email_generator {
            get {
                return ResourceManager.GetString("email_generator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width,initial-scale=1&quot;&gt;
        ///    &lt;meta name=&quot;x-apple-disable-message-reformatting&quot;&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///
        ///    &lt;style&gt;
        ///        table,
        ///        td,
        ///        div,
        ///        h1,
        ///        p {
        ///            font-family: Arial, sans-serif;
        ///        }
        ///
        ///        @media screen and (max-width: 530px) {
        ///             [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string password_generator {
            get {
                return ResourceManager.GetString("password_generator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;title&gt;Pdf Design&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///        }
        ///
        ///        table.border {
        ///            border-collapse: collapse;
        ///        }
        ///
        ///        th {
        ///            padding: 5px;
        ///            text-align: left;
        ///        }
        ///
        ///        table.border td {
        ///            padding: 5px;
        ///        }
        ///    &lt;/style&gt;
        ///
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///    &lt;table style=&quot;width:100%&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td style=&quot;width:20%&quot;&gt; &lt;/td&gt;
        ///            &lt;td style=&quot;width:60%&quot; align=&quot;center&quot;&gt;
        ///    [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string pdf_generator {
            get {
                return ResourceManager.GetString("pdf_generator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;title&gt;Pdf Design&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///        }
        ///
        ///        table.border {
        ///            border-collapse: collapse;
        ///        }
        ///
        ///        th {
        ///            padding: 5px;
        ///            text-align: left;
        ///        }
        ///
        ///        table.border td {
        ///            padding: 5px;
        ///        }
        ///    &lt;/style&gt;
        ///
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///    &lt;table style=&quot;width:100%&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td style=&quot;width:20%&quot;&gt; &lt;/td&gt;
        ///            &lt;td style=&quot;width:60%&quot; align=&quot;center&quot;&gt;
        ///    [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string report_generator {
            get {
                return ResourceManager.GetString("report_generator", resourceCulture);
            }
        }
    }
}
