//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Control
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.SALES_LIN = new HashSet<SALES_LIN>();
        }
    
        public int IDPRODUCT { get; set; }
        public Nullable<int> CODE { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> CATEGORY { get; set; }
        public Nullable<int> SUPPLIER { get; set; }
        public Nullable<int> STOCK { get; set; }
        public Nullable<decimal> SELL_PRICE { get; set; }
        public Nullable<decimal> SUPPLIER_PRICE { get; set; }
    
        public virtual CATEGORY CATEGORY1 { get; set; }
        public virtual SUPPLIER SUPPLIER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALES_LIN> SALES_LIN { get; set; }
    }
}
