//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Control
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALE
    {
        public decimal IDSALE { get; set; }
        public decimal PRODUCT_NUMBER { get; set; }
        public string STATE { get; set; }
        public decimal TOTAL_PRICE { get; set; }
        public decimal IDCONTACT { get; set; }
        public decimal IDPRODUCT { get; set; }
    
        public virtual CONTACT CONTACT { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
