//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Control
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALE
    {
        public int IDSALE { get; set; }
        public Nullable<int> PROD_NUMBER { get; set; }
        public Nullable<int> STATE { get; set; }
        public Nullable<decimal> TOTAL_PRICE { get; set; }
        public Nullable<int> IDCONTACT { get; set; }
        public Nullable<int> IDPRODUCTO { get; set; }
    
        public virtual CONTACT CONTACT { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual STATE STATE1 { get; set; }
    }
}
