//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Control
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALES_CAB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SALES_CAB()
        {
            this.SALES_LIN = new HashSet<SALES_LIN>();
        }
    
        public int IDCAB { get; set; }
        public Nullable<int> STATE { get; set; }
        public Nullable<int> IDCONTACT { get; set; }
        public Nullable<decimal> TOTAL_PRICE { get; set; }
        public string COMENTS { get; set; }
        public Nullable<System.DateTime> FECHA_PEDIDO { get; set; }
    
        public virtual CONTACT CONTACT { get; set; }
        public virtual STATE STATE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALES_LIN> SALES_LIN { get; set; }
    }
}
