//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Control
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PRODUCTS
    {
        public Nullable<int> CODE { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> STOCK { get; set; }
        public Nullable<decimal> SELL_PRICE { get; set; }
        public Nullable<decimal> SUPPLIER_PRICE { get; set; }
        public string CATEGORY { get; set; }
        public string SUPPLIER { get; set; }
        public int IDPRODUCT { get; set; }
        public int IDCATEGORY { get; set; }
        public int IDSUPPLIER { get; set; }
    }
}
